// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestWeb_NguyenLeMinhKhoi.Models;

namespace TestWeb_NguyenLeMinhKhoi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250612071239_InitSchema")]
    partial class InitSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestWeb_NguyenLeMinhKhoi.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Nguyễn Tấn Thành",
                            Price = 300m,
                            Quantity = 2,
                            Title = "Học CSS"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Phạm Đức Trọng",
                            Price = 200m,
                            Quantity = 3,
                            Title = "Học Java"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Phạm Tú",
                            Price = 500m,
                            Quantity = 5,
                            Title = "Học Java Nâng Cao"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Nguyễn Duy",
                            Price = 200m,
                            Quantity = 1,
                            Title = "Kiến thức Word cơ bản"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Phạm Đức Trọng",
                            Price = 200m,
                            Quantity = 1,
                            Title = "Lịch sử"
                        },
                        new
                        {
                            Id = 6,
                            Author = "Phạm Đức Trọng",
                            Price = 200m,
                            Quantity = 1,
                            Title = "Lịch sử VN"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
